application: jasimmkv2
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /(.+)
  static_files: static/\1
  upload: static/(.*)

- url: /
  static_files: static/index.html
  upload: static/index.html

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
- ^(.*/)?tests$
- ^(.*/)?test$
- ^test/(.*/)?
- ^COPYING.LESSER
- ^README\..*
- \.gitignore
- ^\.git/.*
- \.*\.lint$
- ^fabfile\.py
- ^testrunner\.py
- ^grunt\.js
- ^node_modules/(.*/)?
- ^static/node_modules/(.*/)?
- ^static/bower/(.*/)?
- run.sh